Handle access to vssps for PerfStar
dotnet/msbuild pull request #10366
Opened 2024-07-12 18:04 UTC by YuliiaKovalova

## Fixes:
Issues with access to msbuild.exe bit for perfstar run.
In order to secure that, a new SP was created and added to the corresponding organization.

## Validation:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9874247&view=logs&j=063f674e-38db-59b9-8dc6-bda499493784&t=d2d8d882-24a4-5280-d5d8-e137cda2c3ba

2024-07-12 18:56 UTC, JanKrivanek approved these changes
:clap:

2024-07-12 21:57 UTC, rainersigwald approved these changes
I assume that failure is one where we need to refactor to deal with #10299?

2024-07-15 07:58 UTC, YuliiaKovalova commented
> I assume that failure is one where we need to refactor to deal with #10299?

I am not sure it's related.
Hopefully, @AR-May has more insights :)

2024-07-15 08:55 UTC, AR-May requested changes

2024-07-15 08:55 UTC, AR-May commented on .exp-insertions.yml
> +        Write-Host "Setting AzDO.DotnetPerfStarToken: ${token}"
```suggestion
        Write-Host "Setting AzDO.DotnetPerfStarToken"
```

2024-07-15 08:57 UTC, AR-May commented
> > I assume that failure is one where we need to refactor to deal with #10299?
> 
> I am not sure it's related. Hopefully, @AR-May has more insights :)

No, this is unrelated. This is for being able to run msbuild.exe in perf tests.

2024-07-15 08:58 UTC, AR-May approved these changes

2024-07-15 09:31 UTC, merged