Localize the text in the common target
dotnet/msbuild pull request #10388
Opened 2024-07-17 06:19 UTC by JaynieBai

Fixes [#10171 ](https://github.com/dotnet/msbuild/issues/10171)

### Context
MsBuild produces unlocalized messages for some specific validation cases that happen in scope of target.
The example of the task usage: https://github.com/YuliiaKovalova/msbuild/blob/be21253d85f7766356880d376e26aaa69c34c4cd/src/Tasks/Microsoft.Common.CurrentVersion.targets#L862

### Changes Made
Refactor the existing messages with the recently added task allows to produce localized messages:
https://github.com/dotnet/msbuild/blob/79dff86b18613cfe3510b719ac28e8a8c3e7f96c/src/Tasks/MSBuildInternalMessage.cs , produced by with hardcoded text.
### Testing

### Notes

2024-07-22 08:25 UTC, JanKrivanek approved these changes
Looks good.

Though - I was not controllig in detail 1:1 equality of the literals in .targets with the new in resx files - I suppose they were copied over (with just applying format parameters)

2024-07-26 10:12 UTC, Nirmal4G requested changes
Why not use `CommonSdk` instead of `CommonTarget`? It could be useful if you decide to do #1686?

Also, Message Code (like `MSB3539`) should be separately specified to surface them properly in VS IDE's Messages and VS Code's Problems panels.

2024-08-20 19:31 UTC, Nirmal4G requested changes

2024-08-20 19:31 UTC, Nirmal4G commented on src/Tasks/Microsoft.Common.CurrentVersion.targets
> -
nit: undo the line deletion!

2024-08-20 19:31 UTC, Nirmal4G commented on src/Tasks/Microsoft.Common.CurrentVersion.targets
> +    <MSBuildInternalMessage ResourceName="$(_InvalidConfigurationMessageResourceName)" Severity="$(_InvalidConfigurationMessageSeverity)" FormatArguments="$(MSBuildProjectFile);$(_OriginalConfigurati
Sorry about my mistake.

```suggestion
    <MSBuildInternalMessage
      ResourceName="$(_InvalidConfigurationMessageResourceName)"
      Severity="$(_InvalidConfigurationMessageSeverity)"
      FormatArguments="$(MSBuildProjectFile);$(_OriginalConfiguration);$(_OriginalPlatform)"
      Condition="'$(_InvalidConfigurationMessageSeverity)' != ''" />
```

> [!IMPORTANT]
>
> For the condition, we could have used the same output path check here also
> but we must not forget to update both when it changes in the future.
> That's why I have used Severity instead.

2024-08-21 04:37 UTC, Nirmal4G commented on src/Tasks/Microsoft.Common.CurrentVersion.targets
> +      Severity="$(_NonExistentProjectReferenceSecuity)"
```suggestion
      Severity="$(_NonExistentProjectReferenceSeverity)"
```

2024-08-21 06:03 UTC, JaynieBai commented on src/Tasks/Microsoft.Common.CurrentVersion.targets
> +    <MSBuildInternalMessage ResourceName="$(_InvalidConfigurationMessageResourceName)" Severity="$(_InvalidConfigurationMessageSeverity)" FormatArguments="$(MSBuildProjectFile);$(_OriginalConfigurati
Thanks a lot @Nirmal4G

2024-11-27 08:30 UTC, JaynieBai commented on src/Tasks/Microsoft.Common.CurrentVersion.targets
> +    <MSBuildInternalMessage Condition=" '$(_InvalidConfigurationWarning)' == 'true' and '$(BuildingInsideVisualStudio)' != 'true'" ResourceName="CommonTarget.InvalidConfigurationTextWithoutBuildingIn
Updated

2024-11-30 02:23 UTC, Nirmal4G requested changes
Code Style nit: Method parameter should start with lower case.

Other that that, it's looking good.

2024-11-30 02:23 UTC, Nirmal4G commented on src/Tasks.UnitTests/MSBuildInternalMessage_Tests.cs
> +        public void BaseIntermediateOutputPathMisMatchWarning(bool IsInitialMSBuildProjectExtensionsPathEmpty, string expectedResourceName)
```suggestion
        public void BaseIntermediateOutputPathMisMatchWarning(bool isInitialMSBuildProjectExtensionsPathEmpty, string expectedResourceName)
```

2024-11-30 02:23 UTC, Nirmal4G commented on src/Tasks.UnitTests/MSBuildInternalMessage_Tests.cs
> +                        <_InitialMSBuildProjectExtensionsPath>{(IsInitialMSBuildProjectExtensionsPathEmpty ? "" : "obj")}</_InitialMSBuildProjectExtensionsPath>
```suggestion
                        <_InitialMSBuildProjectExtensionsPath>{(isInitialMSBuildProjectExtensionsPathEmpty ? "" : "obj")}</_InitialMSBuildProjectExtensionsPath>
```

2024-11-30 02:23 UTC, Nirmal4G commented on src/Tasks.UnitTests/MSBuildInternalMessage_Tests.cs
> +                if (!IsInitialMSBuildProjectExtensionsPathEmpty)
```suggestion
                if (!isInitialMSBuildProjectExtensionsPathEmpty)
```

2024-12-02 03:33 UTC, JaynieBai commented on src/Tasks.UnitTests/MSBuildInternalMessage_Tests.cs
> +                        <_InitialMSBuildProjectExtensionsPath>{(IsInitialMSBuildProjectExtensionsPathEmpty ? "" : "obj")}</_InitialMSBuildProjectExtensionsPath>
Sorry. missed that. Updated

2024-12-02 03:35 UTC, JaynieBai commented
> > Message Code (like MSB3539) should be separately specified to ensure searchability in these files.
> 
> We only localize the text, so, it's not strictly required to put `Code` in. But I get the reason why. I can also argue that, when debugging an obscure build failure, you might need to locate the line in the targets where it spits out the message and start from there. Since, for almost all messages, the text log does not provide line number and file of the message task unless a high verbosity level is provided. So, you cannot locate the message task.
> 
> With `Code` specified in the targets, we can just do a text search on a preprocessed file, and we can go to that exact line. This saves a ton of time combing through binlog or imported files.
> 
> And if you want to indicate the `Code` mapping in RESX, why not add it in the comments? There's a reason that previous text only message tasks had a separate `Code` parameter instead of just putting them in the `Text` parameter.

Thanks for your explanation. I added that code in the comment.

2024-12-02 04:58 UTC, Nirmal4G commented
> I added that code in the comment.

This works just as fine, but it requires anyone who adds a message task to consistently place the `Code` in the comments, which is improbable. IMO, separating the `Code` from the resource string remains most effective.

Also, `Code` in the resource string seems to be optional even if the Severity is either `Warning` or `Error`. Since this is an internal task to MSBuild, can't we make the `Code` mandatory on those conditions? This would prevent some typos in the future and also force us to allocate `Code` for every warning or error.

2024-12-02 05:03 UTC, Nirmal4G approved these changes

2024-12-05 10:40 UTC, JanKrivanek commented
@Nirmal4G thonks for nice suggestions - tracked as https://github.com/dotnet/msbuild/issues/11087 - as the change would require adjusting code violating this currently and is out of scope of this PR

2024-12-05 10:42 UTC, YuliiaKovalova approved these changes

2024-12-05 10:42 UTC, merged

2024-12-05 10:47 UTC, Nirmal4G commented
@JanKrivanek No problem. As you said, these are **just** suggestions. And I ~~thonk~~ thank you (sorry, couldn't resist 😜) for considering it.

2024-12-06 06:58 UTC, JanKrivanek commented
:laughing: appology - quick typing. I promise I gave more time into considering the suggestion than into to typing that response! 😉 (it's tracked after all)