Move BuildCheck docs
dotnet/msbuild pull request #10399
Opened 2024-07-17 15:10 UTC by JanKrivanek

### Context
We are planning to ship the feature - so let's move specs from proposed space.

### Follow-up work need once merged
* [ ] Update https://aka.ms/buildcheck/codes (btw. is it the one you had in mind @baronfel? Or is there another as well?)
* [ ] Update docs link in https://github.com/dotnet/msbuild/issues/10372 (@f-alizada)

2024-07-17 15:45 UTC, baronfel commented
The other location is the p6 release notes, but I can handle that

2024-07-17 15:45 UTC, baronfel approved these changes

2024-07-18 07:40 UTC, f-alizada requested changes
Thank you for driving this! 
I would expect in this PR only this kind of changes: 
![image](https://github.com/user-attachments/assets/e6685d58-44b0-4c3a-890c-e4f8131e43ed)
Please let me know if that is not the case, and if there are changes could you please point in the PR description what exacly was  updated?

2024-07-18 07:40 UTC, f-alizada commented on documentation/specs/BuildCheck/Codes.md
> +| [BC0102](#BC0102) | Double writes. |
This page seems to not have every code: https://github.com/dotnet/msbuild/blob/main/documentation/specs/proposed/BuildCheck/Codes.md

2024-07-18 09:12 UTC, JanKrivanek commented
@f-alizada thank you for eye for detail! I apparently had some stale branch. Move is fixed now

2024-07-18 09:15 UTC, f-alizada approved these changes
Thank you!

2024-07-18 09:37 UTC, merged