switch to "Pack" target invocation for generating test assests
dotnet/msbuild pull request #10872
Opened 2024-10-23 15:31 UTC by YuliiaKovalova

Fixes:
Floating issue with pipelines:

`dotnet\sdk\9.0.100-rc.2.24474.11\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1005: (NETCORE_ENGINEERING_TELEMETRY=Build) Assets file 'D:\a\_work\1\s\artifacts\obj\StringTools\project.assets.json' doesn't have a target for 'net35'. Ensure that restore has run and that you have included 'net35' in the TargetFrameworks for your project.`

+ issue with missed `pdb` files for the test packages

## Resolution
Using "Pack" target helps to avoid the listed problems. 
Confirmed by several internal runs:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10449114&view=results
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10449354&view=results

2024-10-23 21:48 UTC, rainersigwald requested changes

2024-10-23 21:48 UTC, rainersigwald commented on eng/TestAssets.targets
>      <Exec Command="dotnet pack &quot;%(ProjectsToPack.Identity)&quot; -o &quot;$(ArtifactsNonShippingPackagesDir)&quot; -p:PackageVersion=$(PackageVersion)" />
Could you instead call `dotnet pack --no-restore` here, so it doesn't muck with the assets file from the regular build?

2024-10-24 15:26 UTC, JanKrivanek approved these changes

2024-10-30 11:05 UTC, maridematte approved these changes

2024-10-30 11:22 UTC, merged