Remove unused usings
dotnet/msbuild pull request #5761
Opened 2020-09-30 17:02 UTC by panopticoncentral

Super-minor cleanup, just removes all the unused "using" statements across the project.

2020-09-30 17:06 UTC, Forgind approved these changes
I think this is the first time I've seen GitHub not load diffs because there were too many files rather than because a file was too large.

2020-09-30 17:16 UTC, rainersigwald commented
@panopticoncentral How did you do this? What tool? Were any manual fixups required?

2020-09-30 17:28 UTC, panopticoncentral commented
Just opened in the latest VS, clicked on an unused using and chose "clean up solution." I thought I built retail but guess not! Will fix that up.

If this isn't desirable, it's no big deal to just close, it's just a force of habit for me. :)

2020-09-30 17:29 UTC, panopticoncentral commented
Or maybe it wasn't retail, I may have forgotten to build tests.

2020-10-02 14:07 UTC, ladipro commented on src/Shared/ToolsetElement.cs
> +    #region Private Fields
It looks like the convention, at least in MSBuild, is to align the `#region` / `#endregion` directives same as the enclosed code, so this change is likely not desired.

2020-10-02 14:07 UTC, ladipro commented on src/Tasks/FxCopExclusions/Microsoft.Build.Tasks.Suppressions.cs
> -//
Same here. Is this being deleted intentionally?

2020-10-02 14:07 UTC, ladipro commented on src/Utilities/FxCopExclusions/Microsoft.Build.Utilities.Suppressions.cs
> -//
Same here. Intentional?

2020-10-02 14:07 UTC, ladipro commented on src/Utilities/TrackedDependencies/CanonicalTrackedInputFiles.cs
> +#region Member Data
Undesired indentation change?

2020-10-02 14:07 UTC, ladipro commented on src/Utilities/TrackedDependencies/CanonicalTrackedOutputFiles.cs
> +#region Member Data
Undesired indentation change?

2020-10-02 14:07 UTC, ladipro commented on src/Utilities/TrackedDependencies/DependencyTableCache.cs
> +#region Methods
Undesired indentation change?

2020-10-02 14:07 UTC, ladipro commented on src/Utilities/TrackedDependencies/FileTracker.cs
> +#region Static Member Data
Undesired indentation change?

2020-10-02 14:07 UTC, ladipro commented on src/Utilities/TrackedDependencies/FlatTrackingData.cs
> +#region Constants
Undesired indentation change?

2020-10-05 00:21 UTC, drewnoakes commented
This code fix shouldn't be changing any other code. I'd file a bug against Roslyn for these.

2020-10-05 06:53 UTC, ladipro approved these changes

2020-10-06 22:10 UTC, Forgind approved these changes

2020-10-16 15:59 UTC, rainersigwald requested changes
@Forgind volunteered to get merge conflicts resolved.

2020-10-16 15:59 UTC, rainersigwald commented on src/Deprecated/Engine/Solution/VCProjectParser.cs
> +    static internal class VCProjectParser
Revert whitespace change.

2020-10-20 15:09 UTC, rainersigwald approved these changes

2020-10-20 15:10 UTC, merged

2020-10-20 15:10 UTC, rainersigwald commented
Thanks @panopticoncentral!