Change references from master to main
dotnet/msbuild pull request #6259
Opened 2021-03-15 20:22 UTC by BenVillalobos

Fixes #

### Context

### Changes Made

### Testing

### Notes
Will keep this open for a bit. I may remove master trigger in this PR.

2021-03-15 22:35 UTC, Forgind requested changes
I'd prefer to leave master as a trigger for a week or two until we've had a few successful insertions from main without manual interference. This seems unsafe if we need a hotfix but can't get anything into VS. Can dismiss if the balance is against me.

2021-03-15 23:24 UTC, BenVillalobos commented
@Forgind I'm fine leaving this open until bare minimum one good VS insertion, but this PR should merge before any others.

The outages today have slowed progress on this. /cc: @AR-May when you're around, can you run a pipeline build on main? You'll need to set `OptProfDrop` to `OptimizationData/dotnet/msbuild/master/20210312.1/980986/1` (latest optprof from master), and clear `IbcSourceBranchName`. If it succeeds, kick off a release on main and cross your fingers 🤞

/cc: @marcpopMSFT @ladipro @rokonec

2021-03-15 23:37 UTC, Forgind commented
Not opposed to merging this before anything else, short of a very high-priority fix.

As I understand the outages, we just have no way of running tests right now, so I don't think running the pipeline again would help more than just poking the current PR to run again.

2021-03-16 00:06 UTC, BenVillalobos commented
@Forgind Could just be me, but I haven't noticed the outage affecting CI tests. Kick em both I say ¯\_(ツ)_/¯

2021-03-16 00:16 UTC, Forgind commented
Not CI but look at the reasons for our errors:
https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/310761

2021-03-16 18:53 UTC, AR-May commented
@BenVillalobos The VS insertion from main was successful. Crossed fingers helped.

2021-03-16 18:54 UTC, BenVillalobos commented
@Forgind Merging is blocked on requested changes. Can you approve so we can get this and https://github.com/dotnet/msbuild/pull/6269 merged asap?

2021-03-16 19:08 UTC, Forgind approved these changes

2021-03-16 19:08 UTC, AR-May approved these changes

2021-03-16 19:18 UTC, merged