Update branding for 17.0
dotnet/msbuild pull request #6408
Opened 2021-05-04 14:08 UTC by ladipro

### Context

Mainline development is switching to Visual Studio 17.0.

### Changes Made

Cherry-picking efe639ab78f9f7712e963b55032bc88bd664f6c6 (#6321) and adding a commit with a README.md update.

### Testing

Grepped the tree for other occurrences of 16.10.

### Notes

2021-05-04 14:09 UTC, ladipro commented on README.md
> +We have forked for MSBuild 16.11 in the branch [`vs16.11`](https://github.com/Microsoft/msbuild/tree/vs16.11). Changes to that branch need special approval.
There is a possibility we will still need to service 16.10, although it's not LTS so not mentioning it here.

2021-05-04 14:28 UTC, rainersigwald requested changes
Should we merge the `vs17.0` branch back into main first?

In my head we should do these things, in either order

1. Merge #6361 (maybe with the readme change here added?)
2. Merge `vs17.0` to `main`

I don't think cherry-picking is the right move since we should have clean merges.

2021-05-04 14:34 UTC, ladipro commented
Merging `vs17.0` yields the exact same diff as cherry-picking that one commit. Git-sanity wise it's better to merge, that's a good point.

2021-05-04 15:02 UTC, Forgind commented
I think 1 should go first. It should have been a part of the branding in the first place—it wouldn't make sense to have even a build that's partway between dev16 and dev17.

2021-05-04 19:58 UTC, ladipro commented
@Forgind I am planning to delete `vs17.0` to prevent confusion - `main` is going to be 17.0 and `vs17.0` would be "16.10 with 17.0 branding" which isn't useful. So I was thinking about taking these steps:

1. Merge this PR. The diff is a traditional branding update that's done after cutting a release branch. The reason I am annoyingly insisting on doing that is that it fits the established pattern.
2. Delete the `vs17.0` branch.
3. Repoint #6361 to main and merge. #6361 is a major version branding update so it's great that it has its own PR.

2021-05-04 20:00 UTC, rainersigwald commented
Works for me

2021-05-04 22:03 UTC, rainersigwald approved these changes

2021-05-04 22:14 UTC, Forgind commented
Is there any reason we have to delete vs17.0? We've created vs16.x branches before they're really properly full before. Are we just going slower here because we have so long before 17.0 ships?

Also, are we then planning to have main insert into VS main and rel/d17, or are we planning to abandon rel/d17?

2021-05-05 05:49 UTC, ladipro commented
No strong reason to delete, it's just not needed until the next snap. VS `rel/d17` is also sitting unused until the next preview. We'll be inserting our main into VS main for a few months, ignoring the "17" branches on both ends.

It's a good analogy, though. I'm not deleting and will keep the branch around. Thank you!

2021-05-05 05:51 UTC, merged