Query cache in parallel
dotnet/msbuild pull request #6434
Opened 2021-05-08 21:37 UTC by cdmihai

Depends on #6412. Merge that one in first (or close it and merge this one).

### Context
The project cache was being serially. Oops.
This is because the monolithic BuildManager._syncLock was being held during the cache query, thus serializing all access.

### Changes Made
Broke down the monolithic lock in `ExecuteBuildSubmission(BuildSubmission)` in three successive regions:
1. Compute a BuildRequestConfiguration for the given build submission (and various other arbitrary BM state mutations). Protected by _syncLock.
2. If a cache is present, evaluate the build configuration if necessary (non static graph cache scenarios) and query the cache. Protected by locking each BuildRequestConfiguration. This achieves lock striping and enables parallel access to the cache.
3. Respond to cache query result and do arbitrary BM state mutations. Protected by _synclock.

### Testing
Added a parallel stress test. This should be a good test to both ensure the cache is queried in parallel and to stress test the concurrency in the engine.

2021-05-11 22:18 UTC, Forgind requested changes
This feels like a draft PR with what looks like lots of excess Debug.Asserts and locks. The hanging test is ProjectCacheByBuildParametersAndBottomUpBuildWorks, but in the meantime, I'd suggest looking carefully at various locks to see which are truly necessary, then removing certain locks to see where the hang comes. Since it's consistently failing that particular test, you can use that to help you find the deadlock.

2021-05-11 22:18 UTC, Forgind commented on src/Build/BackEnd/BuildManager/BuildManager.cs
> +            lock (_syncLock)
I'm wondering if it's worth it to try to minimize the time spent in locks, especially this one. Something like:
```C#
if (_projectCacheService == null) {
  // var p = ProjectCacheService.FromDescriptorAsync(...);
  lock (_syncLock) {
    if (_projectCacheService == null) {
      _projectCacheService = p;
    }
  }
}

2021-05-11 22:18 UTC, Forgind commented on src/Build/BackEnd/BuildManager/BuildManager.cs
> +                    lock (_syncLock)
Does any part of this outside of 1098-1106 really need the lock?

2021-05-11 22:18 UTC, Forgind commented on src/Build/BackEnd/BuildManager/BuildManager.cs
> +                    lock (newConfiguration)
Do we actually need a lock if we successfully ensured each configuration is unique and built exactly once?

2021-05-11 22:18 UTC, Forgind commented on src/Build/BackEnd/BuildManager/BuildManager.cs
> +                    {
What part of this needs a lock?

2021-05-11 22:18 UTC, Forgind commented on src/Build/BackEnd/BuildManager/BuildManager.cs
> +                    {
Setting something that's already true to true doesn't seem bad. I'd skip this lock and the if/return.

2021-05-11 22:18 UTC, Forgind commented on src/Build/BackEnd/BuildManager/BuildManager.cs
>              {
Why do you need a lock for this? Everything else should be ended, right?

2021-05-14 00:13 UTC, cdmihai commented
Closing and trying this a new way.

2021-05-14 00:13 UTC, closed without merging