Catch ArgumentException as well as BadImageFormatException when failing because of libraries without resources
dotnet/msbuild pull request #6546
Opened 2021-06-10 19:03 UTC by Forgind

This was a heinous bug to repro.

Using VS 17.0.0+, create a blank UWP app with target platform version 16299 or 17134. Build Debug/x86.
If that doesn't work, clean and build again.
If that doesn't work, clean and build again.

It should work every time, but from my testing, every other clean-build cycle succeeds even following identical steps. Every other build clean-build cycle fails with a message saying an attempt was made to load a file with incorrect format. This is normally a BadImageFormatException and caught (see comment above), but it seems that with dev 17, that is sometimes (always?) wrapped in an ArgumentException and not caught. This fixes that problem by catching both.

Maybe we should verify that the ArgumentException mentions BadImageFormatException before just continuing?

Testing: Several attempted repros in a row succeeded. It had been pretty reliably failing every other time, so that was a shift.

2021-06-10 19:45 UTC, rainersigwald requested changes
I'm concerned that this isn't the full root cause. What is different in dev17? Have you falsified the caching hypothesis I proposed offline?

2021-06-11 16:47 UTC, Forgind commented
The repro seems complicated by `every other clean-build cycle succeeds even following identical steps`. Not sure what could cause that—marcpopMSFT suggested maybe creating a cache then invalidating it on subsequent builds, but if you create a cache, you should use it in the same step, and if you invalidate a cache, you shouldn't use that cache.

That the error message explicitly says it's a BadImageFormatException (even though it's an ArgumentException) and that we were previously catching BadImageFormatExceptions makes me fairly confident it's just a slight change in what error is being thrown. Furthermore, I tried cleaning and building several times with the blanket `catch (ArgumentException)` and the more specialized one I now have, and in both cases, the rate of failure went from 50% to 0% (in my tests), which suggests the same.

2021-06-14 15:17 UTC, rainersigwald commented on src/Tasks/GenerateResource.cs
> +                // BadImageFormatExceptions can be wrapped in ArgumentExceptions, so catch those, too.
We looked at this and found https://referencesource.microsoft.com/#mscorlib/system/reflection/module.cs,857

2021-06-14 15:59 UTC, Forgind commented on src/Tasks/GenerateResource.cs
> +                // BadImageFormatExceptions can be wrapped in ArgumentExceptions, so catch those, too.
```suggestion
                // BadImageFormatExceptions can be wrapped in ArgumentExceptions, so catch those, too. See https://referencesource.microsoft.com/#mscorlib/system/reflection/module.cs,857
```

2021-06-14 16:55 UTC, Forgind commented on src/Tasks/GenerateResource.cs
> +                // BadImageFormatExceptions can be wrapped in ArgumentExceptions, so catch those, too.
Incorporated, thanks!

2021-06-21 18:59 UTC, BenVillalobos approved these changes

2021-06-28 18:03 UTC, rainersigwald approved these changes
Let's go ahead with this since we (sorta) said we'd get it in for preview2.

(I still want to know what's up with the intermittent failure/toggle behavior, but this change looks good independent of that.)

2021-06-29 10:01 UTC, merged