ChangeWave 16.8 Becomes Default Behavior
dotnet/msbuild pull request #6634
Opened 2021-06-29 00:12 UTC by BenVillalobos

### Context
Features under ChangeWave 16.8 are due for becoming normal functionality.

### Changes Made
Removed Wave_16.8 and all checks/tests that had to do with changewave16.8.

### Testing

### Notes

2021-06-29 15:30 UTC, rainersigwald requested changes
Can you update the doc, and also update the doc with the lifespan of a changewave? I had a vague recollection that these would last another two point releases.

2021-06-30 20:31 UTC, BenVillalobos commented
@rainersigwald Had to remind myself as well. Turns out we decided to make waves standard after two waves.

2021-06-30 20:34 UTC, rainersigwald approved these changes

2021-06-30 20:34 UTC, rainersigwald commented on documentation/wiki/ChangeWaves.md
> +A wave of features is set to "rotate out" (ie. become standard functionality) two bands after its release. For example, wave 16.8 stayed opt-out through wave 16.10, becoming standard functionalty whe
```suggestion
A wave of features is set to "rotate out" (i.e. become standard functionality) two bands after its release. For example, wave 16.8 stayed opt-out through wave 16.10, becoming standard functionalty when wave 17.0 is introduced.
```

2021-06-30 22:23 UTC, BenVillalobos commented
/azp run

2021-07-05 17:40 UTC, Forgind approved these changes
💗 deleting code 🙂

2021-07-14 17:07 UTC, merged