Skip Updating CopyComplete Marker When Not Necessary
dotnet/msbuild pull request #6698
Opened 2021-07-21 21:57 UTC by BenVillalobos

Fixes #https://github.com/dotnet/msbuild/issues/6576

### Context
https://github.com/dotnet/msbuild/issues/6576 revealed that the `.copycomplete` file marker is updated even when the `Copy` task in `_GetCopyFilesMarkedLocal` doesn't _actually_ copy anything.

### Changes Made
This change adds an output parameter, `CopiedAtLeastOneFile` that the `Touch` task is now conditioned off of.

### Testing
Tested local builds

### Notes
This could also be done by having an ITaskItem[] that contains all files that were actually copied. Then the touch task could check if that item were empty. I opted for the straightforward route since the ITaskItem[] solution isn't needed yet, and this implementation can easily be changed when we do need that.

2021-07-21 22:02 UTC, BenVillalobos commented
Much like rainer suggested [here](https://github.com/dotnet/msbuild/issues/6576#issuecomment-872340678), I don't think this fixes some other incremental build problems in CSWinRT, but this was certainly a bug for CopyComplete in the first place.

cc @scottj1s

2021-07-22 00:54 UTC, Forgind requested changes
I don't think this is right. First, I imagine things that don't technically move anything around but create links still should have it marked as if something were copied. More importantly, the copy step itself sometimes throws an exception if the file doesn't need to be copied, so CopiedAtLeastOneFile should be set after that.

2021-07-22 18:30 UTC, Forgind approved these changes
Looks good to me!

2021-07-22 18:30 UTC, Forgind commented on src/Tasks/Copy.cs
>              }
```suggestion
            }

            // Files were successfully copied or linked. Those are equivalent here.
           CopiedAtLeastOneFile = true;
```

? Little shorter.

2021-07-26 06:47 UTC, ladipro reviewed
> This could also be done by having an ITaskItem[] that contains all files that were actually copied.

Why doesn't `CopiedFiles` work here?

https://github.com/dotnet/msbuild/blob/65e44d936dcfbac421d0e786dac68ee22edb1d86/src/Tasks/Copy.cs#L136-L140

2021-07-26 06:47 UTC, ladipro commented on src/Tasks/Copy.cs
> +           CopiedAtLeastOneFile = true;
super-nit: This line is not indented properly.

2021-07-26 06:57 UTC, ladipro commented
> Why doesn't CopiedFiles work here?

Found an answer in the issue! Wondering if the name of the new parameter shouldn't be more explicit in encoding the difference between it and non-empty `CopiedFiles`.

2021-07-26 16:58 UTC, BenVillalobos commented
@ladipro Any suggestions? I considered `ActuallyCopiedAtLeastOneFile` but thought that may have been too snarky 😄

2021-07-26 19:25 UTC, ladipro commented
Maybe `SuccessfullyCopiedAtLeastOneFile`?

What **exactly** is the difference between non-empty `CopiedFiles` and this new output parameter being true? That should help come up with the best name, I believe.

2021-07-26 19:26 UTC, Forgind commented
CopiedFiles is nonempty if either it copies files (in which case this is true) or it notices it doesn't have to copy files because it's up-to-date, in which case this would be false.

2021-07-26 19:30 UTC, ladipro commented
Thank you, how about `UpdatedAtLeastOneFile` then? Plus a good comment on the prop.

2021-07-26 20:26 UTC, ladipro approved these changes
Thank you!

2021-07-26 20:33 UTC, Forgind commented
ChangedFileContents? UpdatedAtLeastOneFile feels to me like it's specifically overwriting, whereas this could be making a new file where there wasn't one before.

2021-07-26 20:38 UTC, ladipro commented
`WroteAtLeastOneFile`? `ChangedFileContents` sounds like a prop to hold "contents", i.e. it's not obvious that it's a boolean. But not feeling strongly about it.

2021-07-26 21:17 UTC, Forgind commented
It isn't a huge deal—better would've been to change CopiedFiles, but that isn't an option. I know I've also been annoyed sometimes when there was too much haggling over names 🙂

Whatever you decide, I'm fine with @BenVillalobos

2021-07-26 23:47 UTC, BenVillalobos commented
> I know I've also been annoyed sometimes when there was too much haggling over names

Yeah it gets particularly haggle-some when its public and therefore shouldn't be changed once it's in. `UpdatedAtLeastOneFile` makes slightly less sense when creating a new file. `WroteAtLeastOneFile` makes sense for both creating a link and creating a new file. Going with `WroteAtLeastOneFile` as the final name.

2021-07-27 08:17 UTC, merged