Add new Windows Forms specific props
dotnet/msbuild pull request #6860
Opened 2021-09-16 03:17 UTC by RussKie

Resolves #6858

### Context

Add new properties introduced in https://github.com/dotnet/designs/blob/main/accepted/2021/winforms/streamline-application-bootstrap.md#msbuild-properties

### Test

Tested by updating the local version in C:\Program Files\Microsoft Visual Studio\2022\Preview\Xml\Schemas\1033\MSBuild and verifying in VS

![image](https://user-images.githubusercontent.com/4403806/133543504-d00f1da6-87d4-4fb0-8ccd-2b42e343cad0.png)
![image](https://user-images.githubusercontent.com/4403806/133543494-ff416625-df7c-490f-9222-d9d06ea2d2ed.png)
![image](https://user-images.githubusercontent.com/4403806/133543475-cb44e799-b64c-4377-b177-1454aec063c1.png)

2021-09-16 14:48 UTC, rainersigwald requested changes
These look good but since they are winforms-specific and our XSD isn't aware of that can you add  something along the lines of "Applies only to Windows Forms projects" in each `documentation`?

2021-09-17 01:34 UTC, RussKie commented
Updated

2021-09-17 01:48 UTC, rainersigwald approved these changes

2021-09-17 15:50 UTC, Forgind approved these changes

2021-09-20 16:37 UTC, merged