port comment changes
dotnet/msbuild pull request #7152
Opened 2021-12-14 20:08 UTC by ghogen

Fixes https://github.com/dotnet/msbuild/issues/7151

### Context
Doc comments are changed from time to time in the dotnet-api-docs repo. These changes need to be ported back to the MSBuild source, now that the MSBuild source is being used as the source-of-truth for MSBuild reference docs.

### Changes Made
Comment-only changes in a number of source files.

### Testing

### Notes

2021-12-14 20:18 UTC, rainersigwald approved these changes

2021-12-14 20:18 UTC, rainersigwald commented on src/Framework/Sdk/SdkResolverContext.cs
> +        /// File version is based on commit height from our public git repository. This is informational and not equal to the assembly version.
```suggestion
        /// File version is informational and not equal to the assembly version.
```

(we don't use the commit height any more)

2021-12-14 20:18 UTC, rainersigwald commented on src/Tasks/CodeTaskFactory.cs
> +        /// Initialzes the task factory.
```suggestion
        /// Initializes the task factory.
```

2021-12-14 20:18 UTC, rainersigwald commented on src/Tasks/Copy.cs
> +        /// Gets or sets a value that indicates whether to use Hard Links for the copied files
```suggestion
        /// Gets or sets a value that indicates whether to use hard links for the copied files
```

(this appears to be the Microsoft style per https://docs.microsoft.com/en-us/windows/win32/fileio/hard-links-and-junctions)

2021-12-14 20:18 UTC, rainersigwald commented on src/Tasks/Copy.cs
> +        /// Gets or sets a value that indicates whether to create Symbolic Links for the copied files
```suggestion
        /// Gets or sets a value that indicates whether to create symbolic links for the copied files
```

2021-12-15 23:57 UTC, danmoseley commented
@ghogen just curious, do you do this manually or with a tool like https://github.com/carlossanlop/DocsPortingTool ?

2021-12-16 01:06 UTC, ghogen commented
@danmoseley I did this manually, but yes the DocsPortingTool is designed to handle this kind of thing. It looked like a bit too much overhead for such a small number of changes.

2021-12-16 02:56 UTC, danmoseley commented
@ghogen that's cool, just checking we weren't missing an opportunity to share tech.

2021-12-22 06:19 UTC, Nirmal4G requested changes
Note inside remarks have markdown because of auto conversion but we don't need to copy them exactly as markdown. Just plain text is fine. Same as before.

Also, Type `cref`s are simplified. Some might not have `using`s defined in the file. Check and add necessary `using`s if needed!

2021-12-22 06:19 UTC, Nirmal4G commented on src/Build/Definition/ProjectCollection.cs
> +        /// This is not the <see cref="P:Microsoft.Build.BuildEngine.ToolsetCollection.ToolsVersions*">ToolsetCollection.ToolsVersions</see>.
```suggestion
        /// This is not the <see cref="ToolsetCollection.ToolsVersions"/>.
```

2021-12-22 06:19 UTC, Nirmal4G commented on src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
> +        /// Initializes a new instance of <see cref="T:Microsoft.Build.Logging.BuildEventArgsReader"/> using a <see cref="T:System.IO.BinaryReader"/> instance.
```suggestion
        /// Initializes a new instance of <see cref="BuildEventArgsReader"/> using a <see cref="BinaryReader"/> instance.
```

2021-12-22 06:19 UTC, Nirmal4G commented on src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
> +        /// <param name="binaryReader">The <see cref="T:System.IO.BinaryReader"/> to read <see cref="T:Microsoft.Build.Framework.BuildEventArgs"/> from.</param>
```suggestion
        /// <param name="binaryReader">The <see cref="BinaryReader"/> to read <see cref="BuildEventArgs"/> from.</param>
```

2021-12-22 06:19 UTC, Nirmal4G commented on src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
> +        /// Reads the next log record from the <see cref="T:System.IO.BinaryReader"/>.
```suggestion
        /// Reads the next log record from the <see cref="BinaryReader"/>.
```

2021-12-22 06:19 UTC, Nirmal4G commented on src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
> +        /// The next <see cref="T:Microsoft.Build.Framework.BuildEventArgs" />. If there are no more records, returns <see langword="null" />.
```suggestion
        /// The next <see cref="BuildEventArgs"/>. If there are no more records, returns <see langword="null"/>.
```

2021-12-22 06:19 UTC, Nirmal4G commented on src/Framework/Sdk/SdkResolver.cs
> +        /// </remarks>
```suggestion
        ///  <remarks>
        ///  Note: You must use the <see cref="SdkResultFactory"/> to return a result.
        /// </remarks>
```

2021-12-22 06:19 UTC, Nirmal4G commented on src/Framework/Sdk/SdkResolverContext.cs
> +        /// ]]></format>
```suggestion
        ///     File version is informational and not equal to the assembly version.
```

Do we need to include info about how the file version is calculated?

2021-12-22 06:19 UTC, Nirmal4G commented on src/Framework/Sdk/SdkResult.cs
> +    /// ]]></format>
```suggestion
    ///    Note: Use <see cref="SdkResultFactory"/> to create instances of this class. Do not inherit from this class.
```

2021-12-22 06:19 UTC, Nirmal4G commented on src/Tasks/Hash.cs
> +    /// ]]></format>
```suggestion
    /// Currently uses SHA1. The implementation is subject to change between MSBuild versions.
    /// This class is not intended as a cryptographic security measure, only for uniqueness between build executions.
```

2022-01-03 20:58 UTC, elachlan commented
> Note inside remarks have markdown because of auto conversion but we don't need to copy them exactly as markdown. Just plain text is fine. Same as before.
> 
> Also, Type `cref`s are simplified. Some might not have `using`s defined in the file. Check and add necessary `using`s if needed!

We have a PR for the cref changes at #7194, do we want to merge that first and then rebase this PR?

2022-01-05 18:13 UTC, merged

2022-01-06 05:23 UTC, Nirmal4G commented
@elachlan Then, Can you add these suggestions to that PR? Seems they are not in that PR!?

2022-01-06 05:34 UTC, Nirmal4G commented
@elachlan This is merged, so add these suggestions to your `cref` PR.

2022-01-06 15:28 UTC, Forgind commented
Do we have somewhere we said we want short crefs? I had no idea, but rainersigwald said no.

2022-01-06 15:29 UTC, Forgind commented
If we'd originally listed it as info, that may have been a mistake on our part—if so, sorry about that!

2022-01-06 15:49 UTC, rainersigwald commented
I don't feel strongly about the short/long crefs. I do feel strongly that that style issue shouldn't block this change to reduce pain on our docs partners.

2022-01-07 08:36 UTC, elachlan commented
@ghogen is the markdown important in this issue? Nirmal's suggestions have been applied in another PR and I wanted to make sure whether or not the markdown was required and needed to be preserved.

2022-01-07 17:08 UTC, ghogen commented
@elachlan @Nirmal4G 
The Markdown is used in the dotnet-api-docs repo, but it's only required if there's special formatting such as for a Note/Caution/Tip construct for example. So I think it's OK to implement those suggestions in the other PR.  Note also, we're doing work now to separate the MSBuild API reference from the .NET reference, which will give us more flexibility, because we can control the process better to avoid changes that occur in multiple repos (which is what led to my PR).

2022-01-08 01:11 UTC, Nirmal4G commented
@ghogen

> The Markdown is used in the `dotnet-api-docs` repo, but it's only required if there's special formatting such as for a `Note`/`Caution`/`Tip` construct…

The XML Doc comments already includes all these in the `remarks` element but as plain-text with a heading indicating the intent. Wouldn't it be possible for the doc engine to take it and convert to markdown and convert back to plain-text as is? That way, we wouldn't need those `CDATA` elements in the XML Doc.