SA1643: Finalizer appropriate summary text
dotnet/msbuild pull request #7196
Opened 2022-01-02 07:23 UTC by elachlan

Relates to #7174
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1643.md

2022-01-02 23:48 UTC, sharwell requested changes

2022-01-02 23:48 UTC, sharwell commented on src/Build/BackEnd/BuildManager/BuildManager.cs
>          /// Finalizer
```suggestion
        /// Finalizes an instance of the <see cref="BuildManager"/> class.
```

2022-01-02 23:48 UTC, sharwell commented on src/Build/BackEnd/Components/Caching/RegisteredTaskObjectCache.cs
>          /// Finalizer
```suggestion
        /// Finalizes an instance of the <see cref="RegisteredTaskObjectCache"/> class.
```

2022-01-02 23:48 UTC, sharwell commented on src/Tasks/RCWForCurrentContext.cs
>          /// Finalizer
```suggestion
        /// Finalizes an instance of the <see cref="RCWForCurrentContext{T}"/> class.
```

2022-01-02 23:48 UTC, sharwell commented on src/Build/Collections/ItemDictionary.cs
>              /// Finalizer
```suggestion
            /// Finalizes an instance of the <see cref="Enumerator"/> class.
```

2022-01-02 23:48 UTC, sharwell commented on src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs
>          /// Finalizer
```suggestion
        /// Finalizes an instance of the <see cref="TaskExecutionHost"/> class.
```

2022-01-02 23:48 UTC, sharwell commented on src/Build/BackEnd/Components/Communications/NodeProviderInProc.cs
>          /// Finalizer
```suggestion
        /// Finalizes an instance of the <see cref="NodeProviderInProc"/> class.
```

2022-01-03 16:16 UTC, Forgind approved these changes

2022-01-03 16:26 UTC, sharwell approved these changes

2022-01-10 16:29 UTC, merged