Revert "Loosen version comparisons in loading assemblies (#7042)"
dotnet/msbuild pull request #7415
Opened 2022-02-24 17:31 UTC by rainersigwald

This reverts commit 3bb10b76c5a345b30d6bf55facacbbce47446358.

Fixes #

Work item (Internal use): 

### Summary

### Customer Impact

### Regression?

### Testing

### Risk

2022-02-24 17:32 UTC, Forgind approved these changes

2022-02-24 17:39 UTC, baronfel requested changes
Blocking until we get verification from impacted customers.

2022-02-24 18:18 UTC, baronfel commented
I was able to reproduce the root issue and use the dlls built from this PR to validate the flow.

2022-02-24 18:18 UTC, baronfel approved these changes

2022-02-24 20:24 UTC, merged

2022-03-15 15:02 UTC, baronfel commented
Linking https://github.com/dotnet/msbuild/issues/4081 as a possible required part of this.

2022-08-27 17:59 UTC, jharjung commented
Just FYI, this broke my custom build tasks when a team member updated VS to 17.3.1 which installed the .net 6.0.4 sdk.

Build was fixed by updating nuget packages for Microsoft.Build.* and Microsoft.CodeAnalysis.*. But updating Microsoft.Build.Locator to 1.5.3 ran into this issue: https://github.com/microsoft/MSBuildLocator/issues/176

This was a rather annoying situation to be in. .net 6.0.4 changed the assembly load behavior, which breaks the build, so I have to update nuget packages, but the updated nuget packages have bugs that break that build.

This is most definitely not the first time that changes were made to MSBuild and shipped with minor point releases that ended up breaking my build. I basically have to forbid everyone on my team from ever updating Visual Studio unless/until I give them the go ahead. Otherwise, inevitably, someone will update and not be able to build and I'll have to drop what I'm doing and spend two days researching and resolving obscure issues.

Maybe we could be more conscious of this and try to not have so many breaking changes in MSBuild in minor version .net / VS releases?