17.3 final branding.
dotnet/msbuild pull request #7772
Opened 2022-07-01 12:15 UTC by AR-May

2022-07-01 14:30 UTC, rainersigwald reviewed
LGTM but not pushing the button since we're not ready to merge.

2022-07-01 16:23 UTC, AR-May commented
Could you please request changes, so no merging is guaranteed?

2022-07-01 16:38 UTC, rainersigwald requested changes
LGTM but waiting for finality.

2022-07-14 18:57 UTC, Forgind approved these changes

2022-07-14 19:00 UTC, rainersigwald approved these changes

2022-07-14 19:00 UTC, merged