Allow to set empty string for XmlPoke Value
dotnet/msbuild pull request #8305
Opened 2023-01-12 10:38 UTC by JaynieBai

Fixes [#5814](https://github.com/dotnet/msbuild/issues/5814)

### Context
Can't pass empty string to XmlPoke task.

### Changes Made
Remove the required attribute for Value and the exception when value is null.

### Testing
Unit test XmlPokeWithEmptyValue()

2023-01-16 07:38 UTC, JanKrivanek requested changes
Simple and effective!
I'd suggest to improve the test case to varify the behavior (resulting attribute is present, but empty)

2023-01-16 07:38 UTC, JanKrivanek commented on src/Tasks/XmlPoke.cs
>              set => _value = value;
Do we need the backing field?

2023-01-16 07:38 UTC, JanKrivanek commented on src/Tasks.UnitTests/XmlPoke_Tests.cs
> +        }
We should probably assert here that the target attribute/element is still present, but with empty value.

2023-01-16 07:38 UTC, JanKrivanek commented on src/Tasks.UnitTests/XmlPoke_Tests.cs
> +            string projectContents = @"
No need for change here - just an information. From C# 11 you can use [raw string literals](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11#raw-string-literals) - sou you wouldn't need to combine quotes here.

```C#
string projectContents = """
<Project ToolsVersion="msbuilddefaulttoolsversion">
                <Target Name="Poke">
                    <XmlPoke Value="" Query="//class/variable/@Name" XmlInputPath="{0}"/>
                </Target>
                </Project>""";
```

2023-01-16 14:05 UTC, JanKrivanek approved these changes
Looks good!
Thank you for updating the test case!

2023-01-16 19:34 UTC, Forgind approved these changes
LGTM!

2023-01-18 03:21 UTC, JaynieBai commented
@ghogen  This PR make making the Value property of XmlPoke task optional. please help update document https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/xmlpoke-task.md

2023-01-18 03:22 UTC, merged