Adding in option to filter projects that DynamicPlatformResolution was unable to resolve
dotnet/msbuild pull request #8882
Opened 2023-06-14 15:50 UTC by MIchaelRShea

…

Fixes #

### Context
Currently dynamic platform resolution will leave the "platform" global property of a depending project blank if it is unable to determine the correct architecture to build a project as. This is helpful but in certain situations, especially traversal style projects it makes more sense to remove dependent projects that don't build as a compatible platform.

### Changes Made
I added a property that can be added to projects so that if dynamic platform resolution is unable to determine what platform a project should be built as it will be removed from the graph.

### Testing

### Notes

linking bug https://github.com/dotnet/msbuild/issues/8890

2023-06-14 17:15 UTC, JanKrivanek commented
@MIchaelRShea Thank you for your contribution.
Can you crerate/link a bug describing the issue? This would help properly triaging and processing this PR.

2023-06-16 14:13 UTC, MIchaelRShea commented
> @MIchaelRShea Thank you for your contribution. Can you crerate/link a bug describing the issue? This would help properly triaging and processing this PR.

Yes went ahead and linked a bug to this PR

2023-07-11 08:26 UTC, JanKrivanek requested changes
Overall looks good.

I just wish for higher clarity for future maintanance of the code - especially by adding documentation of the added property and it's expected behavior

2023-07-11 08:26 UTC, JanKrivanek commented on src/Build/Graph/ProjectInterpretation.cs
> +        private const string EnableDynamicPlatformFilteringPropertyName = "EnableDynamicPlatformFiltering";
This should be mentioned in https://github.com/dotnet/msbuild/blob/main/documentation/ProjectReference-Protocol.md

2023-07-11 08:26 UTC, JanKrivanek commented on src/Build.UnitTests/Graph/GetCompatiblePlatformGraph_Tests.cs
> +                // yet still default to the same platform.
I might be just slow - but this comment is very hard to understand. Especially the `where a project has global platform set and does not have global platform set` feels wrong.
Can it be restated?

2023-07-11 08:26 UTC, JanKrivanek commented on src/Build.UnitTests/Graph/GetCompatiblePlatformGraph_Tests.cs
> +        [Fact]
Turning this into theory with positive and negative case (2.proj set for matching and mismatching platform, then the expected number of nodes should be 1 and 0 respectively)

2023-07-11 08:26 UTC, JanKrivanek commented on src/Build/Graph/ProjectInterpretation.cs
> +                        continue;
Project being removed from graph might deserve low-priority log message for clarity during troubleshooting.

2023-10-10 14:18 UTC, closed without merging