Add unit test for https://github.com/dotnet/msbuild/pull/8870
dotnet/msbuild pull request #8961
Opened 2023-06-27 09:37 UTC by JaynieBai

Fixes #

### Context

### Changes Made

### Testing

### Notes

2023-06-29 08:25 UTC, JanKrivanek requested changes
Looks as a good starting point.
I believe we need to add custom `IDictionary` implementation and verification of the resulting task output in order to test the fix

2023-06-29 08:25 UTC, JanKrivanek commented on src/Build.UnitTests/BackEnd/TaskExecutionHost_Tests.cs
> +        public IDictionary CloneCustomMetadata() => new Dictionary<string, string>(metaData);
I believe we need a custom `IDictionary` implementation (not `Dictionary<string, string>`) here to test the https://github.com/dotnet/msbuild/pull/8870 fix

2023-06-29 08:25 UTC, JanKrivanek commented on src/Build.UnitTests/BackEnd/TaskExecutionHost_Tests.cs
> +            MockLogger ml = ObjectModelHelpers.BuildProjectExpectSuccess($"""
nit: Do not store the return value unless required

2023-06-29 08:25 UTC, JanKrivanek commented on src/Build.UnitTests/BackEnd/TaskExecutionHost_Tests.cs
> +        public void TestTaskDictionaryOutputItems()
Can this somehow test as well that the output has the expected metadata (to verify that the fix aids to properly copying of the metadata)

2023-07-03 02:04 UTC, JaynieBai commented
/azp run

2023-07-26 18:56 UTC, rainersigwald approved these changes
LGTM and I believe addresses @JanKrivanek's concerns.

2023-07-27 13:26 UTC, JanKrivanek approved these changes
Thanks!

2023-07-28 02:15 UTC, merged