Use distinct signal to wait to cancel the submission
dotnet/msbuild pull request #9326
Opened 2023-10-13 07:49 UTC by GangWang01

Fixes #9298

### Context
Waiting using `Thread.Sleep(500)` in the test is unreliable.

### Changes Made
Wait until the specified log appears rather than `Thread.Sleep(500)`.

### Testing

### Notes

2023-10-18 12:49 UTC, JanKrivanek requested changes
Looks as a good way to get rid of some of the pesky flakyness - great!

I'd love to see the test to not iterate the log events repetitively. We can use MockLogger to avoid the additional thread/task and 'wake-check-sleep' pattern here

2023-10-18 12:49 UTC, JanKrivanek commented on src/Build.UnitTests/BackEnd/TaskBuilder_Tests.cs
> +                Func<bool> isSleepCommandExecuted = () => logger.AllBuildEvents.Any(a => unescapedSleepCommand.Equals(a.Message));
While accomplishing the purpose, it feels superfluous to iterate all the log events over and over again (I guess it risk getting the collection modified exception as well).

It should be easy to check only the new events (if any) on each try

2023-10-18 12:49 UTC, JanKrivanek commented on src/Build.UnitTests/BackEnd/TaskBuilder_Tests.cs
> +                Func<bool> isSleepCommandExecuted = () => logger.AllBuildEvents.Any(a => unescapedSleepCommand.Equals(a.Message));
It seems [`AdditionalHandlers`](https://github.com/dotnet/msbuild/blob/f4fa6bde775a3f7cbb2bb90a349ee5fc759114f3/src/Shared/UnitTests/MockLogger.cs#L248C53-L248C71) can be leveraged here - by registering a handler that would set some waithandle upon receiving the required log entry

2023-10-19 12:07 UTC, JanKrivanek requested changes

2023-10-20 06:17 UTC, JanKrivanek approved these changes
Thank you!

2023-10-20 10:44 UTC, YuliiaKovalova approved these changes

2023-10-23 01:54 UTC, merged