Keep the encoding of standard output & error consistent with the console code page
dotnet/msbuild pull request #9539
Opened 2023-12-14 09:12 UTC by GangWang01

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1388756/

### Context
With OS language English and VS language JPN, building newly created CMake project named `プロジェクト` got garbage characters in the output.

### Changes Made
Make the encoding of process standard output & error consistent with the console code page.

### Testing
Added unit tests.

### Notes

2023-12-18 14:39 UTC, rokonec approved these changes

2023-12-21 22:50 UTC, Forgind commented
This doesn't seem like a bad change, and I haven't checked whether it actually fixes the bug or not. It looks like I looked at this bug over two years ago and thought the problem may have been because the Message task didn't support changing the code page directly and may have been that the user needed to change how they were using a ToolTask. Assuming this does fix the problem, though this sounds like a positive change, I'd say it suggests the problem should have been fixed by whoever implemented the ToolTask that is ultimately broken; all they would've had to do is set that property as you did here except in their ToolTask extension. In fact, I'd argue that's a better fix, as this one changes fairly fundamental behavior in MSBuild, which always has potential to cause someone issues even if the change looks benign.

Just my 2c 🙂

2024-01-11 13:02 UTC, JanKrivanek approved these changes
Overall looks good

2024-01-11 13:02 UTC, JanKrivanek commented on src/Utilities/ToolTask.cs
> +                        StandardErrorEncoding = encoding;
Looks good - it just might be sfer to put this behind changewave (in case it breaks anybody)

2024-03-12 09:26 UTC, JanKrivanek requested changes
Please try to see if we can can move the logic to property initialization.

If not - let's discuss other alternatives

2024-03-14 10:11 UTC, GangWang01 commented on src/Utilities/ToolTask.cs
> +                        }
Agree.

2024-03-14 11:42 UTC, JanKrivanek approved these changes
Looks good!

2024-03-18 06:35 UTC, merged