Improve ConfigurableForwardingLogger
dotnet/msbuild pull request #9578
Opened 2023-12-29 12:11 UTC by JanKrivanek

### Context
Random find - `ConfigurableForwardingLogger` is checking a string dictionary for each build event, while a simple events (un)subscriptions can achieve same job with less efforts (coding and CPU)

### Testing
Existing tests ([`ConfigureableForwardingLogger_Tests`](https://github.com/dotnet/msbuild/blob/main/src/Build.UnitTests/ConfigureableForwardingLogger_Tests.cs))

2024-01-02 22:03 UTC, Forgind approved these changes
♥️

2024-01-02 22:03 UTC, Forgind commented on src/Deprecated/Engine/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs
> +        private void SetForwardingBasedOnVerbosity(IEventSource eventSource)
This is only called once per logger and at initialization time, correct? How are double subscriptions possible?

2024-01-03 13:04 UTC, JanKrivanek commented
Note - I accidentally eddited the Deprecated sources version - so porting the changes to the proper source.

Btw. - I cannot wait till we'll finally geer rid of the Deprecated sources!! :-)

2024-01-03 13:37 UTC, JanKrivanek commented on src/Deprecated/Engine/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs
> +        private bool forwardLowImportnaceMessages, forwardNormalImportnaceMessages, forwardHighImportnaceMessages, forwardTaskCommandLine;
Good catch - I needed to go letter by letter to see the actual difference :-D

2024-01-03 20:01 UTC, rokonec requested changes

2024-01-03 20:40 UTC, Forgind commented on src/Build/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs
> +                    eventSource.StatusEventRaised -= BuildStatusHandler;
I'm not 100% sure of this, but it would be nice if you can make it a bit more generic, i.e.,
HandleEvent(eventSource.ProjectStarted, ForwardEvent);

2024-01-03 20:42 UTC, Forgind commented on src/Build/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs
> +                eventSource.TargetFinished += ForwardEvent;
You mean line 265?

2024-01-03 20:43 UTC, Forgind commented on src/Build/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs
> +                _forwardTaskCommandLine = true;
These are both covered above, right? Just delete them?

2024-01-03 21:30 UTC, rokonec commented on src/Build/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs
> +                eventSource.TargetFinished += ForwardEvent;
No I mean missing `_forwardTaskCommandLine = true` somewhere here

2024-01-03 21:35 UTC, rokonec commented on src/Build/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs
> +                eventSource.TargetFinished += ForwardEvent;
Wait a minute, .... I must have reviewed code without last commit.... It is fixed now.

2024-01-03 21:38 UTC, rokonec commented on src/Build/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs
> +                    eventSource.StatusEventRaised -= BuildStatusHandler;
I am not sure if it is possible since every event is different type. At least I don't know how to do that without heavy reflections work.

2024-01-03 21:39 UTC, rokonec approved these changes
My previous review was without last commit, now it looks good to go.

2024-01-04 08:25 UTC, JanKrivanek commented on src/Build/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs
> +                eventSource.TargetFinished += ForwardEvent;
Sorry for churn and for wasted reviewing effort.

I blame it on the presence of deprecated code. We should realy push on getting rid of it - this is not the first time when it cost me some extra time (not counting all those gazillions of times per day when I searh through the types and everything is twice in the results, but one of them is just 'clickbait trap' :-))

2024-01-04 09:30 UTC, JanKrivanek commented on src/Build/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs
> +                    eventSource.StatusEventRaised -= BuildStatusHandler;
Events are special beasts - even if all the events would have same type, it still would not be possible - as it is not allowed to pass event as an argument.

But let me add all those methods as extensions for a general usage by any code that would wish - that way the chatty code will not look so overkill

2024-01-04 09:31 UTC, JanKrivanek commented on src/Build/Logging/DistributedLoggers/ConfigurableForwardingLogger.cs
> +        private void SetForwardingBasedOnVerbosity(IEventSource eventSource)
I prefer having it explicit that subscriptions can happen only during the construction.

2024-01-06 19:47 UTC, merged

2024-01-16 10:58 UTC, ladipro commented
@JanKrivanek this change broke terminal logger output, can you please investigate?

To reproduce, build the MSBuild repo with `/tl`. With this change it's missing most of the `Project tfm succeeded (N.Ns) → path/to/output` log lines.

**Good:**
![image](https://github.com/dotnet/msbuild/assets/12206368/09ff98dd-5b0e-415d-a261-de721f770585)
&lt;snip&gt;

**Bad:**
![image](https://github.com/dotnet/msbuild/assets/12206368/a460b688-7947-45a8-8e80-2b32c9b8b1f7)