Analyzers acquisition experience
dotnet/msbuild pull request #9977
Opened 2024-04-08 10:34 UTC by YuliiaKovalova

2024-04-10 13:27 UTC, JanKrivanek reviewed
Will need to do deeper pass for approve/request changes result - but overall looks good.

It feels this deserves a section in documentation

2024-04-10 13:27 UTC, JanKrivanek commented on src/Build/Evaluation/Expander.cs
> +                            if (TryGetArg(args, out string arg0) && _loggingContext != null)
nit - the second check seems much cheaper - so it should be frontloaded

```suggestion
                            if (_loggingContext != null && TryGetArg(args, out string arg0))
```

2024-04-10 13:27 UTC, JanKrivanek commented on src/Build/Resources/Strings.resx
Need to be edited manually

2024-04-10 13:31 UTC, YuliiaKovalova commented on src/Build/Evaluation/Expander.cs
> +        private readonly LoggingContext _loggingContext;
I am not sure if it's a good idea to mention IBuildCheckManager in Expander.
@rainersigwald , what do you think?

2024-04-10 13:32 UTC, YuliiaKovalova commented on src/Build/BuildCheck/Acquisition/BuildCheckAcquisitionModule.cs
> +        public BuildAnalyzerFactory? CreateBuildAnalyzerFactory(AnalyzerAcquisitionData analyzerAcquisitionData)
need to discuss it offline

2024-04-12 08:54 UTC, JanKrivanek requested changes
Looks good!

I added couple comments - the double iteration in acquisition module is reason for requesting changes, but otherwise it looks good!

2024-04-12 08:54 UTC, JanKrivanek commented on src/Build/BuildCheck/Acquisition/BuildCheckAcquisitionModule.cs
> +                if (analyzerTypes.Any())
This (and the foreach below) will leave to double enumearation and call of `GetTypes`. Let's just replace it with the check of emptiness of the `analyzersFactory` list below. Creation of an empty list has negligable cost compared to the acquisition form single package

2024-04-12 08:54 UTC, JanKrivanek commented on src/Build/BuildCheck/Acquisition/BuildCheckAcquisitionModule.cs
> +                    var analyzersFactory = new List<BuildAnalyzerFactory>();
NIT: should be plural

```suggestion
                    var analyzersFactories = new List<BuildAnalyzerFactory>();
```

2024-04-12 08:54 UTC, JanKrivanek commented on src/Build/BuildCheck/Acquisition/BuildCheckAcquisitionModule.cs
> +                if (analyzerTypes.Any())
Oh - you are returning empty enumerable below - so then you don't even need to check anything here

2024-04-12 08:54 UTC, JanKrivanek commented on src/Build/BuildCheck/Infrastructure/BuildCheckConnectorLogger.cs
> +            handler(e);
I love this - thanks!

2024-04-12 08:54 UTC, JanKrivanek commented on src/Build/BuildCheck/Infrastructure/IBuildCheckManager.cs
> +namespace Microsoft.Build.Experimental.BuildCheck
nit: files scoped namespace removed here

2024-04-12 08:54 UTC, JanKrivanek commented on src/Build/Evaluation/Expander.cs
> +        private readonly LoggingContext _loggingContext;
My request is controversial (at the very least) and your solution satisfies current requirements - so let's defer the discussion until it's relevant.
Sorry for confusion!

2024-04-15 18:57 UTC, closed without merging